feat: Initial version (#2)
* initial version

* style(terraform fmt): format code

* docs(terraform-docs): update readme

---------

Co-authored-by: Michael Ullrich <michael.ullrich@acai.gmbh>
Co-authored-by: github-actions <noreply@github.com>

diff --git a/.github/workflows/terraform-module.yml b/.github/workflows/terraform-module.yml
--- a/.github/workflows/terraform-module.yml
+++ b/.github/workflows/terraform-module.yml
@@ -9,18 +9,20 @@ on:
       - main
 
 jobs:
-  tfc-module-base-job:
-    uses: acai-consulting/github-terraform-workflows/.github/workflows/tfc-module-base.yml@main
+  tf_module_base_job:
+    uses: acai-consulting/github-terraform-workflows/.github/workflows/tf-module-base.yml@main
     if: ${{ github.event_name == 'pull_request' }}
     with:
       tflint_config_repo: "acai-consulting/github-workflow-configs"
       tflint_config_repo_ref: "main"
       tflint_config_path: ".tflint.hcl"
-
-  tfc-module-test-job:
-    needs: tfc-module-base-job
+      
+  tf_module_test_job:
+    needs: tf_module_base_job
     uses: acai-consulting/github-terraform-workflows/.github/workflows/tfc-module-test.yml@main
-    if: ${{ github.event_name == 'pull_request' }}
+    if: ${{ 
+      needs.tf_module_base_job.outputs.all_steps_passed == 'true' &&
+      github.event_name == 'pull_request' }}
     with:
       terratest_config_repo: "acai-consulting/github-workflow-configs"
       terratest_config_repo_ref: "main"
@@ -31,20 +33,27 @@ jobs:
       AWS_TESTBED_SECRET_ACCESS_KEY: ${{ secrets.AWS_TESTBED_SECRET_ACCESS_KEY }}
       AWS_TESTBED_DEFAULT_REGION: ${{ secrets.AWS_TESTBED_DEFAULT_REGION }}
 
-  consume-outputs:
-    needs: [tfc-module-base-job, tfc-module-test-job]
-    runs-on: ubuntu-latest
+  tf_check_for_allowed_merge:
+    needs: [tf_module_base_job, tf_module_test_job]
+    if: ${{  github.event_name == 'pull_request' }}
+    runs-on: "ubuntu-latest"
     steps:
-      - name: Use Outputs from Reusable Workflow
+      - name: Check for failure condition        
         run: |
-          echo "Fmt Status: ${{ needs.tfc-module-base-job.outputs.fmt_status }}"
-          echo "Docs Status: ${{ needs.tfc-module-base-job.outputs.docs_status }}"
-          echo "Lint Status: ${{ needs.tfc-module-base-job.outputs.lint_status }}"
-          echo "Fmt Diff Exists: ${{ needs.tfc-module-base-job.outputs.fmt_diff_exists }}"
-          echo "Docs Diff Exists: ${{ needs.tfc-module-base-job.outputs.docs_diff_exists }}"
-
-  tfc-module-release:
-    uses: acai-consulting/github-terraform-workflows/.github/workflows/tfc-module-release.yml@main
+          # Check if all steps in tf_module_base_job have passed
+          if [ "${{ needs.tf_module_base_job.outputs.all_steps_passed }}" != 'true' ]; then
+            echo "Base job failed, failing the workflow"
+            exit 1
+          fi
+          # Check if all steps in tf_module_test_job have passed
+          if [ "${{ needs.tf_module_test_job.outputs.all_steps_passed }}" != 'true' ]; then
+            echo "Test job failed, failing the workflow"
+            exit 1
+          fi
+          echo "All checks passed, proceeding to release"
+                
+  tfc_module_release:
+    uses: acai-consulting/github-terraform-workflows/.github/workflows/tf-module-release.yml@main
     if: ${{ github.event_name == 'push' }}
     with:
       semantic_release_config_repo: "acai-consulting/github-workflow-configs"
